springdoc:
  packages-to-scan: com.inner.circle.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    default-model-rendering: example
    operations-sorter: alpha

---
spring:
  config:
    activate:
      on-profile: local
  mvc:
    async:
      request-timeout: 180000

swagger:
  server-url: http://localhost:10001

---
spring:
  config:
    activate:
      on-profile: dev
  mvc:
    async:
      request-timeout: 180000

swagger:
  server-url: https://payment.pay-200.com
