spring:
  application:
    name: api
  profiles:
    active: local
    include: infra, openapi, core, metric
  jackson:
    deserialization:
      use-big-decimal-for-floats: true
  mvc:
    async:
      request-timeout: 180000

server:
  servlet:
    session:
      timeout: 10m
  port: 8080
card:
  url:
    base-url: http://localhost:8082
    approve-end-point: /mock/card/approve
    validate-end-point: /mock/card/validate

logging:
    discord:
        webhook-url: "none"

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 10001

card:
  url:
    base-url: https://mock.pay-200.com
    approve-end-point: /mock/card/approve
    validate-end-point: /mock/card/validate

---
spring:
  config:
    activate:
      on-profile: dev
    import: aws-secretsmanager:/secret/pay200

card:
  url:
    base-url: https://mock.pay-200.com
    approve-end-point: /mock/card/approve
    validate-end-point: /mock/card/validate

logging:
    discord:
        webhook-url: ${DISCORD_WEB_HOOK_URL}
